version: 2

sources:
  - name: im_data_pipeline
    description: "Source data for IM Data Test models"
    database: im-data-platform-prod
    schema: account
    tables:
      - name: accounts
        description: "Table containing account data"
        identifier: accounts