name: Deploy Airflow Environment
# This workflow is triggered on pushes to specific branches[dev, main] or manually. 
# It orchestrates the deployment process by calling the reusable workflow (airflow_environment_template.yaml) for each target environment (dev, production), providing environment-specific configurations.

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'dags/**'
      - 'im_data_pipeline/**'
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy to Dev Environment
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/airflow_environment_template.yaml # Calling the reusable workflow
    permissions:  
      contents: 'read'
      id-token: 'write'
    with:
      environment: development
    secrets:
      WIF_PROVIDER: ${{ secrets.DEV_WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.DEV_WIF_SERVICE_ACCOUNT }}

  deploy-prod:
    name: Deploy to Production Environment
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/airflow_environment_template.yaml # Calling the reusable workflow
    permissions:  
      contents: 'read'
      id-token: 'write'
    with:
      environment: production
    secrets:
      WIF_PROVIDER: ${{ secrets.PROD_WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.PROD_WIF_SERVICE_ACCOUNT }}