name: 'Deploy Terraform - Development'

on:
  push:
    branches:
      - dev
    paths:
      - 'terraform/environments/dev/**'
      - 'terraform/modules/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'terraform/environments/dev/**'
      - 'terraform/modules/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform-dev:
    uses: ./.github/workflows/terraform-template.yml
    with:
      environment: development
      working_directory: ./terraform/environments/dev
      target_branch: dev
    secrets:
      WIF_PROVIDER: ${{ secrets.DEV_WIF_PROVIDER }}
      WIF_SERVICE_ACCOUNT: ${{ secrets.DEV_WIF_SERVICE_ACCOUNT }}